### ISSUE TITLE
error undefined

### ISSUE THREAD

**Issue by spcsmrf** [spraakbanken/sparv-backend#1]
i dont know where to post this but the sparv website dosent seem to work since yesterday (if i remember correctly), i have tested on multiple devices

it gives one error and one warning

``Importkedjan gav följande felmeddelanden:``

and

``Importkedjan gav följande varningar:
undefined``

**Comment by anne17** [comment]
Thanks for your report! The backend was down but now it's up and running again. If you continue to have trouble with the Sparv web service you're welcome to contact sb-sparv@svenska.gu.se. If you include the hash of your build it will be easier for us to figure out what went wrong.
