### ISSUE TITLE
connect: Connecting to socket failed: Connection refused make: *** [annotations/fileids] Fel 1

### ISSUE THREAD

**Issue by spcsmrf** [spraakbanken/sparv-backend#3]
Happens whatever the input is

Importkedjan gav följande felmeddelanden:

No result found. Something went wrong in the corpus pipeline.

Stderr:

connect: Connecting to socket failed: Connection refused
make: *** [annotations/fileids] Fel 1

**Comment by anne17** [comment]
Fixed for now be restarting the backend. There is some underlying error though which has not been fixed yet, so this can happen again (see issue #4 ).
